/* eslint-disable @typescript-eslint/no-explicit-any */
'use client';

import React, { useState } from 'react';
import { useRouter, useParams } from 'next/navigation';
import { useRescheduleBooking } from '@/hooks/useBookingManagement';
import { useSingleBooking } from '@/hooks/useSingleBooking'; // ⬅️ Use the efficient hook
import { Card, CardHeader, CardTitle, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Loader2, ArrowLeft, CalendarDays, Save, Clock, BookOpen } from "lucide-react";
import Link from 'next/link';
import { format } from 'date-fns';
import { toast } from 'react-toastify';
import BookingCalendar from '@/components/Student/bookings/BookingCalendar'; // Assuming this path
import StudentLayout from '../../_layout';

export default function StudentReschedulePage() {
    const params = useParams();
    const router = useRouter();
    const bookingId = params?.id as string;

    // 1. Fetch the single, specific booking record
    const { data: currentBooking, isLoading, error } = useSingleBooking(bookingId);
    const { mutate: reschedule, isPending: isRescheduling } = useRescheduleBooking();

    // State for the new slot selection
    const [newSlot, setNewSlot] = useState<any>(null);
    // 🚨 Helper to safely convert Firestore Timestamp object to JavaScript Date
    const getTime = (timestamp: any): Date => {
        const seconds = timestamp?._seconds ?? timestamp?.seconds;
        const nanoseconds = timestamp?._nanoseconds ?? timestamp?.nanoseconds ?? 0;

        if (typeof seconds === 'number') {
            const totalMilliseconds = (seconds * 1000) + (nanoseconds / 1000000);
            return new Date(totalMilliseconds);
        }
        return new Date();
    };


    if (isLoading || !bookingId) {
        return <Loader2 className="h-10 w-10 animate-spin text-gray-500 mx-auto mt-20" />;
    }

    if (error || !currentBooking) {
        return <p className='text-center mt-20 text-red-500'>Booking not found or access denied.</p>;
    }

    // Tutor data is enriched in the useSingleBooking hook response
    const tutor = currentBooking.tutor;

    const handleReschedule = () => {
        if (!newSlot || !newSlot.startTime || !newSlot.endTime) {
            return toast.error("Please select a new time slot.");
        }

        reschedule({
            bookingId: currentBooking.id,
            // Pass the UTC ISO strings generated by the calendar
            newStartTime: newSlot.startTime,
            newEndTime: newSlot.endTime,
        }, {
            onSuccess: () => {
                // Redirect user back to the main booking list after success
                router.push('/student/bookings');
            },
            onError: (err: any) => {
                toast.error(err?.response?.data?.error || "Failed to reschedule lesson.");
            },
        });
    };

    return (
        <StudentLayout>
            <div className="p-6 md:p-10 min-h-screen bg-gray-50">
                <Link href="/student/bookings">
                    <Button variant="outline" className="mb-6"><ArrowLeft className="h-4 w-4 mr-2" /> Back to Schedule</Button>
                </Link>

                <Card className="shadow-lg rounded-xl">
                    <CardHeader>
                        <CardTitle className="text-2xl font-bold text-slate-800 flex items-center gap-2">
                            Reschedule Lesson with {tutor?.name}
                        </CardTitle>
                    </CardHeader>
                    <CardContent className="grid grid-cols-1 lg:grid-cols-3 gap-6">

                        {/* Current Booking Summary */}
                        <div className="lg:col-span-3 space-y-4 p-4 py-2 border rounded-xl bg-slate-50">
                            <h4 className="text-lg font-semibold">Current Slot</h4>
                            {/* <p className="text-sm text-slate-600 flex items-center gap-2">
                                <BookOpen className="h-4 w-4" />
                                {currentBooking.subject}
                            </p> */}
                            <p className="text-sm text-slate-600 flex items-center gap-2">
                                <CalendarDays className="h-4 w-4" />
                                {/* 🚨 FIX: Use getTime helper */}
                                Old Date: {format(getTime(currentBooking.startTime), 'PPP')}
                            </p>
                            <p className="text-sm text-slate-600 flex items-center gap-2">
                                <Clock className="h-4 w-4" />
                                Old Time: {format(getTime(currentBooking.startTime), 'p')}
                            </p>

                            {/* New Slot Display */}
                            {newSlot && (
                                <div className='mt-4 pt-4 border-t border-dashed'>
                                    <h4 className="text-md font-bold text-green-600">New Slot Selected</h4>
                                    <p className="text-sm text-green-600">
                                        {format(new Date(newSlot?.startTime), 'PPP')} at {format(new Date(newSlot.startTime), 'p')}
                                    </p>
                                </div>
                            )}
                        </div>

                        {/* New Slot Selection Calendar */}
                        <div className="lg:col-span-3">
                            <h4 className="text-lg font-semibold mb-3">Select New Time</h4>
                            <BookingCalendar
                                // Pass the tutor object which contains the availability rules and timeZone
                                tutor={tutor}
                                onSlotSelect={(slot) => setNewSlot(slot[0])} // Set state with new slot
                                selectedSlots={newSlot ? [newSlot] : []} // Highlight the single new selection
                            />
                            <div className="mt-6 flex justify-end">
                                <Button
                                    onClick={handleReschedule}
                                    disabled={isRescheduling || !newSlot}
                                    className="gap-2"
                                >
                                    {isRescheduling ? <Loader2 className="h-4 w-4 animate-spin" /> : <Save className="h-4 w-4" />}
                                    Confirm Reschedule
                                </Button>
                            </div>
                        </div>
                    </CardContent>
                </Card>
            </div>
        </StudentLayout>
    );
}